apiVersion: v1alpha1
kind: Fleet
metadata:
  name: basic-nginx-fleet
spec:
  selector:
    matchLabels:
      fleet: basic-nginx-fleet
  template:
    spec:
      os:
        image: quay.io/flightctl/flightctl-agent-basic-nginx:{{ device.metadata.labels[basic-nginx-version] }}
      config:
        - name: motd-update
          configType: InlineConfigProviderSpec
          inline:
            ignition:
              version: 3.4.0
            storage:
              files:
                - contents:
                    source: >-
                      data:,This%20system%20is%20managed%20by%20flightctl.%0A
                  mode: 422
                  overwrite: true
                  path: "/etc/motd"
      systemd:
        matchPatterns:
          - "microshift.service"
          - "crio.service"
          - "flightctl-agent.service"
